/* Browser adapter for the actual native WXML/TypeScript source. No duplicated domain logic. */
const cache={},pages={},templates={},view=document.getElementById('view');let current=null,currentRoute='today',renderQueued=false;
const assetRoot=new URL('../',document.currentScript.src),asset=path=>new URL(path,assetRoot).href;
const getJSON=key=>{try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}};
const saveJSON=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
const virtualURL=path=>path?.startsWith('preview-file://')?getJSON(path):path;
function fetchSync(url){const x=new XMLHttpRequest();x.open('GET',url,false);x.send();if(x.status!==200)throw new Error(`Cannot load ${url}`);return x.responseText;}
function requireModule(path){let key=new URL(path,assetRoot).href;if(!key.endsWith('.js'))key+='.js';if(cache[key])return cache[key].exports;const module={exports:{}};cache[key]=module;const directory=new URL('.',key);new Function('require','module','exports',fetchSync(key)+'\n//# sourceURL='+key)(relative=>requireModule(new URL(relative,directory).href),module,module.exports);return module.exports;}
function toast(title){const el=document.createElement('div');el.className='toast';el.textContent=title;document.body.appendChild(el);setTimeout(()=>el.remove(),2200);}
function setPath(object,path,value){const parts=path.replace(/\[(\d+)\]/g,'.$1').split('.');let target=object;for(const p of parts.slice(0,-1)){target[p]??={};target=target[p];}target[parts.at(-1)]=value;}
function dispatch(handler,dataset,value){if(!handler||!current[handler])return;const event={currentTarget:{dataset},detail:{value}};Promise.resolve(current[handler](event)).catch(e=>{console.error(e);toast(e.message||'操作失败');});}
const wx=window.wx={
 getStorageSync:getJSON,setStorageSync:saveJSON,removeStorageSync:key=>localStorage.removeItem(key),
 showToast:({title})=>toast(title),showModal:({title,content,confirmText='确定',cancelText='取消'})=>new Promise(resolve=>{const overlay=document.createElement('div');overlay.className='modal-overlay';const box=document.createElement('div');box.className='modal-box';const heading=document.createElement('h3');heading.textContent=title;const body=document.createElement('p');body.textContent=content;const footer=document.createElement('div');footer.className='modal-actions';for(const [label,ok] of [[cancelText,false],[confirmText,true]]){const button=document.createElement('button');button.textContent=label;button.className=ok?'primary':'ghost';button.onclick=()=>{overlay.remove();resolve({confirm:ok,cancel:!ok});};footer.appendChild(button);}box.append(heading,body,footer);overlay.appendChild(box);document.body.appendChild(overlay);}),
 getNetworkType:({success})=>success({networkType:'wifi'}),onNetworkStatusChange(){},
 canIUse:()=>false,setClipboardData:async({data})=>{try{await navigator.clipboard.writeText(data);toast('已复制')}catch{prompt('复制以下内容',data)}},
 switchTab:({url})=>navigate(url.split('/')[2]),nextTick:fn=>setTimeout(fn,0),
 chooseMedia:({count})=>new Promise((resolve,reject)=>{const input=document.createElement('input');input.type='file';input.accept='image/*';input.multiple=true;input.addEventListener('change',async()=>{const files=Array.from(input.files||[]).slice(0,count),out=[];for(const f of files){const src=await new Promise(r=>{const reader=new FileReader();reader.onload=()=>r(reader.result);reader.readAsDataURL(f);});out.push({tempFilePath:src});}if(!out.length)return reject({errMsg:'chooseMedia:cancel'});resolve({tempFiles:out});});input.addEventListener('cancel',()=>reject({errMsg:'chooseMedia:cancel'}));input.click();}),
 compressImage:async({src,quality})=>{const image=new Image();image.src=src;await image.decode();const canvas=document.createElement('canvas');const scale=Math.min(1,1400/Math.max(image.width,image.height));canvas.width=image.width*scale;canvas.height=image.height*scale;canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);return {tempFilePath:canvas.toDataURL('image/jpeg',quality/100)};},
 getFileSystemManager:()=>({saveFile({tempFilePath,success,fail}){try{const key='preview-file://'+Date.now()+'-'+Math.random().toString(36).slice(2);saveJSON(key,tempFilePath);success({savedFilePath:key});}catch(e){fail(e)}}}),
 previewImage:({current})=>{const overlay=document.createElement('div');overlay.className='overlay';const image=document.createElement('img');image.src=virtualURL(current);overlay.appendChild(image);overlay.onclick=()=>overlay.remove();document.body.appendChild(overlay);},
 createSelectorQuery(){let selector,callback;const query={in(){return query},select(s){selector=s;return query},boundingClientRect(fn){callback=fn;return query},exec(){const el=document.querySelector(selector);callback?.(el?el.getBoundingClientRect():null);}};return query;},
 createCanvasContext(id){const canvas=document.querySelector('[data-canvas="'+id+'"]');if(!canvas)return {};canvas.width=canvas.clientWidth;canvas.height=canvas.clientHeight;const ctx=canvas.getContext('2d');return {...Object.fromEntries(['clearRect','beginPath','moveTo','lineTo','stroke','fillText','arc','fill'].map(k=>[k,(...a)=>ctx[k](...a)])),setFontSize:n=>ctx.font=n+'px sans-serif',setFillStyle:c=>ctx.fillStyle=c,setStrokeStyle:c=>ctx.strokeStyle=c,setLineWidth:n=>ctx.lineWidth=n,draw(){}};}
};
window.App=()=>{};window.Page=options=>{options.data=JSON.parse(JSON.stringify(options.data));options.setData=function(changes){for(const [path,value] of Object.entries(changes))setPath(this.data,path,value);queueRender();};pages[currentRoute]=options;};
function expression(code,scope){try{return new Function('scope','with(scope){return ('+code+')}')(scope)}catch(e){console.warn('WXML expression',code,e.message);return undefined}}
function attr(value,scope){const pieces=value.match(/\{\{[\s\S]*?\}\}/g);if(pieces?.length===1&&pieces[0]===value)return expression(value.slice(2,-2),scope);return value.replace(/\{\{([\s\S]*?)\}\}/g,(_,code)=>expression(code,scope)??'');}
function px(value){return String(value).replace(/(-?\d+(?:\.\d+)?)rpx/g,(_,n)=>Number(n)/2+'px');}
function nodeHas(node,name){return node.hasAttribute?.(name)}
function children(parent,scope){const result=document.createDocumentFragment();let matched=false,inChain=false;for(const node of parent.childNodes){if(node.nodeType===3){if(node.textContent.trim())result.appendChild(document.createTextNode(attr(node.textContent,scope)));continue;}if(node.nodeType!==1)continue;const conditional=nodeHas(node,'wx:if'),otherwise=nodeHas(node,'wx:else'),elseif=nodeHas(node,'wx:elif');if(conditional){inChain=true;matched=!!attr(node.getAttribute('wx:if'),scope);if(!matched)continue;}else if(otherwise||elseif){if(!inChain||matched)continue;matched=otherwise||!!attr(node.getAttribute('wx:elif'),scope);if(!matched)continue;}else{inChain=false;matched=false;}result.appendChild(renderNode(node,scope));}return result;}
function renderNode(node,scope,loop=false){
 if(nodeHas(node,'wx:for')&&!loop){const frag=document.createDocumentFragment(),items=attr(node.getAttribute('wx:for'),scope)||[];items.forEach((item,index)=>{const inner={...scope,[node.getAttribute('wx:for-item')||'item']:item,[node.getAttribute('wx:for-index')||'index']:index};frag.appendChild(renderNode(node,inner,true));});return frag;}
 const tag=node.tagName;if(tag==='block')return children(node,scope);
 const mapping={view:'div',text:'span',image:'img',switch:'input','checkbox-group':'div',checkbox:'input',picker:'div',canvas:'canvas'};
 const el=document.createElement(mapping[tag]||tag),values={},dataset={};for(const a of node.attributes){if(a.name.startsWith('wx:'))continue;values[a.name]=attr(a.value,scope);if(a.name.startsWith('data-'))dataset[a.name.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=values[a.name];}
 if(values.class)el.className=values.class;if(values.id)el.id=values.id;if(values.style)el.setAttribute('style',px(values.style));
 const eventName=values.bindtap||values.catchtap;if(eventName)el.addEventListener('click',event=>{event.stopPropagation();dispatch(eventName,dataset,undefined);});
 if(tag==='image'){el.src=virtualURL(values.src)||'';el.alt='成长照片';}
 else if(tag==='switch'||tag==='checkbox'){el.type='checkbox';el.classList.add('wx-switch');el.checked=!!values.checked;el.value=values.value||'';el.addEventListener('change',()=>{if(tag==='switch')dispatch(values.bindchange,dataset,el.checked);else{const group=el.closest('[data-checkbox-group]');if(group)dispatch(group.dataset.checkboxGroup,{},[...group.querySelectorAll('input:checked')].map(i=>i.value));}});}
 else if(tag==='input'||tag==='textarea'){el.value=values.value??'';el.type=['number','digit'].includes(values.type)?'number':'text';if(el.type==='number')el.step='any';el.placeholder=values.placeholder||'';if(values.maxlength)el.maxLength=Number(values.maxlength);el.disabled=!!values.disabled;el.addEventListener('input',()=>dispatch(values.bindinput,dataset,el.value));}
 else if(tag==='picker'){el.classList.add('wx-picker');el.appendChild(children(node,scope));const select=document.createElement(values.mode==='date'||values.mode==='time'?'input':'select');if(values.mode==='date'||values.mode==='time'){select.type=values.mode;select.value=values.value||'';if(values.end)select.max=values.end;select.style.cssText='position:absolute;inset:0;opacity:0;width:100%;cursor:pointer';}else{for(const [index,item] of (values.range||[]).entries()){const opt=document.createElement('option');opt.value=index;opt.textContent=values['range-key']?item[values['range-key']]:item;select.appendChild(opt);}select.value=values.value||0;}select.addEventListener('change',()=>dispatch(values.bindchange,dataset,select.value));el.appendChild(select);}
 else if(tag==='canvas'){el.dataset.canvas=values['canvas-id'];}
 else{el.appendChild(children(node,scope));if(tag==='checkbox-group')el.dataset.checkboxGroup=values.bindchange;if(tag==='button'){el.disabled=!!values.disabled;if(values['open-type']==='share')el.onclick=()=>toast('微信分享需在真实小程序中使用');}}
 for(const [key,value] of Object.entries(dataset))el.dataset[key]=typeof value==='object'?JSON.stringify(value):value??'';
 return el;
}
function queueRender(){if(renderQueued)return;renderQueued=true;queueMicrotask(()=>{renderQueued=false;if(!current)return;const active=document.activeElement;const focus=active&&view.contains(active)?{field:active.dataset.field,form:active.dataset.form,index:active.dataset.index,selection:active.selectionStart}:null;const scroll=view.scrollTop;view.replaceChildren(children(templates[currentRoute],current.data));view.scrollTop=scroll;if(focus?.field){const el=[...view.querySelectorAll('input,textarea')].find(el=>el.dataset.field===focus.field&&el.dataset.form===focus.form&&el.dataset.index===focus.index);if(el){el.focus({preventScroll:true});try{el.setSelectionRange(focus.selection,focus.selection)}catch{}}}});}
function navigate(route){current?.onHide?.();currentRoute=route;if(!pages[route]){const source=fetchSync(asset('miniprogram/pages/'+route+'/index.wxml')).replace(/wx:else(?=[\s>])/g,'wx:else=""');const xml=source.replace(/\{\{[\s\S]*?\}\}/g,match=>match.replace(/&/g,'&amp;').replace(/</g,'&lt;'));const doc=new DOMParser().parseFromString('<root xmlns:wx="urn:wx">'+xml+'</root>','application/xml');if(doc.querySelector('parsererror'))throw new Error(doc.querySelector('parsererror').textContent);templates[route]=doc.documentElement;requireModule(asset('.preview-build/pages/'+route+'/index'));pages[route].onLoad?.({});}current=pages[route];view.scrollTop=0;document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.route===route));queueRender();current.onShow?.();}
const routes=[['today','◷','今天'],['feed','♡','喂食'],['growth','❀','成长'],['profile','⌂','档案']];for(const [route,icon,title]of routes){const button=document.createElement('button');button.dataset.route=route;button.innerHTML='<span>'+icon+'</span>'+title;button.onclick=()=>navigate(route);document.getElementById('nav').appendChild(button);}
document.getElementById('native-style').textContent=px(fetchSync(asset('miniprogram/app.wxss')).replace(/\bpage\b/g,'.phone'));
navigate('today');window.addEventListener('beforeunload',()=>current?.onHide?.());
